name: evaluacion
description: "A new Flutter project."
environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  image_picker: ^0.8.7+3
  http: ^1.4.0
  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true